[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "buckstream-client"
version = "1.0.0"
description = "Isomorphic, zero-dependency storage broker SDK client for BuckStream"
readme = "README.md"
requires-python = ">=3.7"
license = { text = "Apache-2.0" }
authors = [
    { name = "Parth Tiwari" }
]
keywords = [
    "buckstream",
    "storage",
    "broker",
    "s3",
    "gcs",
    "sdk",
    "client"
]
dependencies = [
    "requests>=2.20.0"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

[tool.hatch.build.targets.wheel]
packages = ["buckstream.py"]
